Gemfile, Gemfile.lock
Gemfileにgemを追加しました。
「#Gworks add」というコメントの直下に記載しました。
bundle installすればインストールはできますが、実際に利用できるかは都度確認が必要です。
=> Add Gemfile

app/controllers/carts_controller.rb, app/views/carts/index.html.erb
=> created carts controller and cart_items model

Gemfile, Gemfile.lock
seeds.rb作成のためgemを追加しました。
【サンプル】
irb(main):001:0> Gimei.name.kanji
=> "大島 尚登"
irb(main):002:0> Faker::Name.name
=> "Mr. Hye Feil"
irb(main):003:0
=> Add Gemfile seeds

db/migrate/20191112094503_rename_firsrt_name_column_to_customers.rb, db/migrate/20191112094527_rename_firsrt_furigana_column_to_customers.rb, db/migrate/20191112094538_rename_adress_column_to_customers.rb, db/schema.rb, db/seeds.rb
customerモデルのカラム名が間違っていたので修正しました。
修正したカラム
firsrt_furighana
firsrt_name
adress
=> Fix customer_column_rename & seeds.rb sample

app/controllers/carts_controller.rb, app/controllers/items_controller.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/item.rb, app/views/carts/index.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/schema.rb
カートに追加する機能を作りました。
まだうまく保存される状態にありません。
引き続き作業します。
=> Add cart item function

app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb
route.rbを修正したことでヘッダーに記載の下記リンクがエラーになったので修正しました。
-ログイン
-ログアウト
-会員登録
=> Fix application.html.erb path

app/models/like.rb, db/migrate/20191113072202_create_likes.rb, db/schema.rb, test/fixtures/likes.yml, test/models/like_test.rb
=> Add Like model

app/assets/javascripts/users.coffee, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/destroy.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb, app/views/users/update.html.erb, config/routes.rb, db/seeds.rb, test/controllers/users_controller_test.rb
routes.rbを設定しましたが、  
deviseの設定の兼ね合いで名前付きルートが若干わかりづらいです。
scope :users do
get    '/:id(.:format)',      to: 'users#show',    as: :show_customer
patch  '/:id(.:format)',      to: 'users#update',  as: :update_customer
get    '/:id/edit(.:format)', to: 'users#edit',    as: :edit_customer
delete '/:id(.:format)',      to: 'users#destroy', as: :destroy_customer
end
データの再投入
- rails db:reset
- rails db:seed
=> My page controller & Fix seeds.rb

app/controllers/carts_controller.rb, app/models/artist.rb, app/models/disk.rb, app/models/item.rb, app/models/track.rb, app/views/carts/index.html.erb, app/views/items/show.html.erb, db/migrate/20191113110706_create_disks.rb, db/migrate/20191113111000_create_tracks.rb, db/migrate/20191113111113_create_artists.rb, db/schema.rb, db/seeds.rb, test/fixtures/artists.yml, test/fixtures/disks.yml, test/fixtures/tracks.yml, test/models/artist_test.rb, test/models/disk_test.rb, test/models/track_test.rb
モデルを３つ作成しました。
カート内商品一覧の表示を正しくしました。
=> Create model all

app/models/customer.rb, app/models/delivery.rb, db/migrate/20191113115753_create_deliveries.rb, db/migrate/20191114035149_remove_last_name_from_deliveries.rb, db/migrate/20191114035539_add_last_name_to_deliveries.rb, db/migrate/20191114040941_add_not_null_to_deliveries.rb, db/schema.rb, db/seeds.rb, test/fixtures/deliveries.yml, test/models/delivery_test.rb
追加後にnot null入れるの忘れたのに気付いたので
マイグレーションファイルが増えました。
=> Deliveries model

db/seeds.rb
=> Add like to seeds.rb

app/controllers/items_controller.rb, app/controllers/likes_controller.rb, app/models/item.rb, app/views/items/show.html.erb, app/views/likes/index.html.erb, db/seeds.rb
いいねできるようになりましたが
細かいデザインや文言はまだ実装していません。
【対応内容】
- ### 商品詳細でのいいね機能
非会員向けのいいね機能について決めていなかった気がします。  
現状非会員向けに対してはいいね機能を非表示にしていますが、
表示だけはさせた方がよろしいでしょうか？
- ### マイページでのいいね一覧表示
- ### seeds.rb でのいいねの初期データのコメントアウト
初期データがあると逆に邪魔だったのでコメントアウトしています。
いいねの初期データが必要な方はローカル環境でコメントアウトをはずしてください。
=> Add Like feature

app/assets/javascripts/deliveries.coffee, app/assets/stylesheets/deliveries.scss, app/controllers/deliveries_controller.rb, app/controllers/users_controller.rb, app/helpers/deliveries_helper.rb, app/models/delivery.rb, app/views/users/show.html.erb, config/routes.rb, db/seeds.rb, test/controllers/deliveries_controller_test.rb
マイページのお届け先の追加と削除機能を追加しました。
追加ボタンでフォームを表示させる実装はjavascriptが必要だと思いますが、
あまり知識がないので後回しにします。
=> Add delivery feature(create&destroy)

app/controllers/carts_controller.rb, app/views/carts/index.html.erb, app/views/carts/info.html.erb, config/routes.rb
カートの数量を変更して、支払方法・配送先情報画面へ移動の際に上書き保存できるようになりました。
支払選択、配送先フォームはこれからです。
=> added_order_function

app/controllers/items_controller.rb, app/views/items/index.html.erb, app/views/items/show.html.erb, app/views/likes/_ranks.html.erb, db/seeds.rb
1. @likes_ranks
本来は***昨日***から一週間前までを集計対象にしますが、
昨日からだと確認しづらいので***一時的に当日***から一週間前までを集計してます。
画面設計に入ったら本番用のインスタンス変数に切り替えます。（**忘れそう！！**）
1. @likes_ranks_count 
いいね数の合計です。
ワイヤーフレームだといいね数は表示してませんが、
確認しやすくするために一時的に追加しました。
**念のため改めて確認ですが、ランキングにいいね数の合計は表示させなくてよろしいでしょうか?**
1. @ranks_number 
順位を連番で入れる方法が見つからなかったので配列に1~5まで連番で入れました。
---
細かなデザインはしてませんが、indexとshowでそれぞれ部分テンプレートを適用しました。
=> ランキング機能の追加

app/assets/javascripts/info.coffee, app/assets/stylesheets/info.scss, app/controllers/admin/items_controller.rb, app/controllers/info_controller.rb, app/controllers/items_controller.rb, app/helpers/info_helper.rb, app/models/item.rb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/info/index.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, config/routes.rb, db/seeds.rb, test/controllers/info_controller_test.rb
user側にて、詳細検索を追加しましたが、分岐が出来ていないためボタンのみの表示になります。
admin側では、商品削除が行えるようになりました。
=> Select bottun

db/seeds.rb
表題の通りです。
なお、リレーションの関係からエラーになってしまったので
前後関係を若干変えました。
=> seeds.rbに収録曲(track,disk)を追加しました

app/controllers/application_controller.rb, app/views/admins/sessions/new.html.erb, app/views/admins/shared/_links.html.erb
エンドユーザと管理者でログイン画面を分けました。
また、ログイン後のリダイレクト先をapplication_controllerで設定しました。
=> 管理者のログイン画面を作成しました

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb
管理者によるユーザ情報の編集および退会させる機能を追加しました。
=> 管理者のユーザ情報の編集機能&退会機能

app/assets/javascripts/admin/deviveries.coffee, app/assets/stylesheets/admin/deviveries.scss, app/controllers/admin/deliveries_controller.rb, app/controllers/admin/deviveries_controller.rb, app/helpers/admin/deviveries_helper.rb, app/views/admin/customers/show.html.erb, config/routes.rb, test/controllers/admin/deviveries_controller_test.rb
=> 管理者の追加のお届け先削除機能

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/admin/items_controller.rb, app/models/disk.rb, app/models/item.rb, app/views/admin/items/_disk_fields.html.erb, app/views/admin/items/_track_fields.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, config/routes.rb
add/remove にてフォームの増減が行えます。
今後カラム内にて、
disk_numberとtrack_number のデフォルト値を 1 に設定する予定です。
=> admin 商品追加画面と編集画面にフォームを追加しました。

app/controllers/admin/arrived_items_controller.rb, app/controllers/admin/ready_items_controller.rb, app/views/admin/arrived_items/index.html.erb, app/views/admin/ready_items/index.html.erb
細かい実装はできていないですが、とりあえず登録はできるようになりました。
paramsで商品情報と登録日がわかれているので、
それらをmap!で合体させてからsaveしています。わかりづらいと思います。
登録した入荷一覧や登録する際の日付を選ばせる機能はこれからです。
https://github.com/gworks-github/naganoenbando/blob/754dec2f2fed9f7a560cdedb8eab5b690d291567/app/controllers/admin/arrived_items_controller.rb#L6-L23
=> 入荷登録画面から一括で登録できるようになりました。

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/admin/arrived_items_controller.rb, app/views/admin/arrived_items/index.html.erb, app/views/admin/ready_items/index.html.erb
カレンダーから日付と時間を選べるようになったのと、入荷一覧を作成しました。
入荷一覧の検索機能がこれから実装します。
pullした後bundle installしないとサーバが起動しないかもしれません
追加したgem
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'jquery-turbolinks'
https://github.com/gworks-github/naganoenbando/blob/c1ffa8b5bb48cd5de1b571154f0d5be6dd277df4/app/views/admin/ready_items/index.html.erb#L43-L55
=> 入荷一覧の作成とカレンダーからの日付選択

app/controllers/admin/arrived_items_controller.rb, app/controllers/admin/customers_controller.rb, app/controllers/admin/deliveries_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/admin/orders_controller.rb, app/controllers/admin/ready_items_controller.rb, app/views/admin/customers/index.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb
エンドユーザーと管理者で切り替えています。
ページの移動がしやすくなるので、早めにマージしたほうがいいかと思います。
=> ヘッダーとサイドバーを作りました。

app/assets/stylesheets/application.scss, app/assets/stylesheets/items.scss, app/views/items/index.html.erb, config/initializers/kaminari_config.rb, db/seeds.rb
top 画面表示をデザインしました。
kaminariでのページングは、rails g kaminari:config　までの為、実装はまだです。
サイドバーは、まだデザイン変更していません。
=> ユーザー側　TOP画面デザイン

db/seeds.rb
商品数を増やしました。
また、商品の金額を現実的な金額にしました。
=> seedを修正しました

app/models/item.rb
下記の対応をしました。
【エラー】入荷予定に入れた商品を削除した場合 #77
=> 入荷履歴のエラー対応

app/assets/stylesheets/admin/info.scss, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
ほとんどのタグの初期設定マージンが０になりました。
かなり詰まって見えるので、それぞれ設定してください。
=> フォントカラー変えました。

app/assets/stylesheets/admin/admin.scss, app/assets/stylesheets/admin/arrived_items.scss, app/assets/stylesheets/admin/items.scss, app/assets/stylesheets/application.scss, app/views/admin/arrived_items/index.html.erb, app/views/admin/artist/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb, config/initializers/assets.rb
=> 管理者側のデザインを進めています。

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/users/show.html.erb
マイページのデザインしました。
ボタンを押すと追加登録のフォームを表示させるようにしました。
カレンダー同様にtubolink対策でヘッダーのマイページへのリンクの際は
turbokinkを無効にしています。
お届け先の追加のエラーメッセージが表示されないので、
その対応はこれから行います。
=> マイページのデザインしました

app/assets/stylesheets/application.scss, app/views/admin/arrived_items/index.html.erb, app/views/admin/artist/edit.html.erb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/genre/edit.html.erb, app/views/admin/info/index.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/admin/label/edit.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/admin/ready_items/index.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/application.html.erb
=> 管理側のデザインが完成しました。

app/controllers/likes_controller.rb, app/views/likes/index.html.erb
商品一覧の表示を流用したため、
ワイヤーフレームとはことなっています。
=> いいね一覧の画面をデザインしました

app/assets/stylesheets/application.scss, app/views/users/destroy.html.erb
=> 退会確認ページを作成しました。

app/assets/stylesheets/application.scss, app/controllers/items_controller.rb, app/views/items/index.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, config/initializers/kaminari_config.rb
ユーザーTOP下位にページネーションを追加しました。
ワイヤーフレーム通り、1ページ18枚仕様です。
デザインを変更時は、viewsのkaminariから変更可能です。
=> ページネーションを追加しました。

db/seeds.rb
item_id=1の商品だけ二枚組にしてます。
１枚目15曲、2枚目5曲の構成です。
=> seedに二枚組の商品を追加しました

app/assets/javascripts/application.js
また javascriputが起動しなくなったので、
application.jsの関数を修正しました。
=> turbolinks起動　対応

app/assets/stylesheets/application.scss, app/views/items/show.html.erb, app/views/likes/_ranks.html.erb
商品詳細画面にて、trackのテーブルが表示できるようになりました。
=> ユーザー　商品詳細画面について

app/views/devise/sessions/new.html.erb
前回のエラーメッセージがログイン画面に残る件ですが、
一瞬エラーメッセージが表示された後に消えます
、、この仕様で許してください、、
=> ログイン画面にエラーが残る件

app/assets/stylesheets/application.scss
フッター追加に伴う、ログイン、会員登録、マイページのデザイン変更を行いました。
=> ユーザー側　デザイン変更

app/views/items/show.html.erb
=> 商品詳細のいいねボタンの点

app/views/admins/registrations/new.html.erb, app/views/admins/sessions/new.html.erb, config/locales/devise.ja.yml
エラーメッセージを表示させました。
カラムの日本語化のためconfig/locales/devise.ja.ymlを修正しました。
=> 管理者のログイン・登録画面のエラーメッセージ追加

app/assets/stylesheets/application.scss, app/controllers/admins/confirmations_controller.rb, app/controllers/admins/omniauth_callbacks_controller.rb, app/controllers/admins/passwords_controller.rb, app/controllers/admins/registrations_controller.rb, app/controllers/admins/sessions_controller.rb, app/controllers/admins/unlocks_controller.rb, app/models/item.rb, app/views/admin/items/show.html.erb, app/views/admins/registrations/new.html.erb, app/views/admins/sessions/new.html.erb, app/views/items/show.html.erb, app/views/layouts/admin.html.erb
管理者側ログイン画面のデザインと商品詳細のboolean型表記を直しています。
=> 管理者側ログイン画面のデザイン

app/controllers/items_controller.rb, app/models/item.rb
検索機能がある画面でページネーションを導入する際は、
検索機能のメソッドにも「page(params[:page]).per(18)」を追加してください。
def search
修正前    @items = Item.item_search(params)
修正後    @items = Item.item_search(params).page(params[:page]).per(18)
あとアーティストの検索が間違っていたので修正しました。
=> ユーザの商品一覧の商品検索のエラー解消しました

app/controllers/carts_controller.rb, app/views/carts/index.html.erb
必須要件ではないですができそうな気がしたので作ってみました。
在庫数を超えた注文数でレジに進むとエラーになります。
=> 在庫数と越える注文はレジに進ませない機能

app/views/devise/sessions/new.html.erb
ログアウトしたときのメッセージがずっと残ってしまうので修正しました。
=> ユーザのログイン画面の表示修正

config/application.rb, config/locales/cust.yml, config/locales/deli.yml, config/locales/devise.ja.yml
エラーメッセージの日本語化対応が影響していたみたいなので、
設定直しました。
=> 商品登録の不具合対応（ロケールの修正）

app/controllers/items_controller.rb
indexに在庫情報追加されたので、検索機能にも在庫情報を追加しました。
エラーはでなくなりました。
=> ユーザ　商品検索　エラー対応
